#!/usr/bin/env bash
set -euo pipefail

# atcoder-libの#[snippet]付きコードをVS Code用スニペットへ変換する。
# 共通libは編集せず、.tools/配下の一時crateからpath moduleとして読む。
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LIB_DIR="$ROOT_DIR/references/atcoder-lib"
SNIPPET_BIN="$ROOT_DIR/.tools/bin/cargo-snippet"
WORK_DIR="$ROOT_DIR/.tools/snippet-workspace"
OUTPUT_PATH="$ROOT_DIR/.vscode/rust.code-snippets"

if [[ ! -x "$SNIPPET_BIN" ]]; then
    echo "Error: cargo-snippet is not installed in .tools/bin."
    echo "Run: cargo install cargo-snippet --root .tools --features binaries"
    exit 1
fi

if [[ ! -d "$LIB_DIR" ]]; then
    echo "Error: common library was not found: $LIB_DIR"
    exit 1
fi

mkdir -p "$WORK_DIR/src"
trap 'rm -rf "$WORK_DIR"' EXIT

printf '%s\n' \
    '[package]' \
    'name = "ahc-snippet-workspace"' \
    'version = "0.1.0"' \
    'edition = "2021"' \
    'publish = false' \
    '' \
    '[dependencies]' \
    'cargo-snippet = "0.6.5"' > "$WORK_DIR/Cargo.toml"

printf '%s\n' '// Generated by scripts/sync-vscode-snippets.sh. Do not edit.' > "$WORK_DIR/src/lib.rs"
for source_path in "$LIB_DIR"/*.rs; do
    file_name="$(basename "$source_path")"
    module_name="${file_name%.rs}"
    [[ "$module_name" == "lib" ]] && continue
    cp "$source_path" "$WORK_DIR/src/$file_name"
    printf 'mod %s;\n' "$module_name" >> "$WORK_DIR/src/lib.rs"
done

temporary_output="$(mktemp "$OUTPUT_PATH.XXXXXX")"
trap 'rm -rf "$WORK_DIR" "$temporary_output"' EXIT

(
    cd "$WORK_DIR"
    CARGO_NET_OFFLINE=true "$SNIPPET_BIN" snippet -t vscode
) | sed -E 's/"prefix"/"scope": "rust",\n    "prefix"/' > "$temporary_output"

mv "$temporary_output" "$OUTPUT_PATH"
echo "Updated: $OUTPUT_PATH"
